### PR TITLE
feat: Add subscription sub-module

### PR DESCRIPTION
**Pull request by matheusmazzoni**
## Description

Added an sns subscription submodule

## Motivation and Context

The motivation for this would be that when it is necessary to integrate an sns (account A) and sqs (account B) between aws accounts, we have the following scenarios:
  1. The subscription is in account A, where the SNS is located
  2. The subscription is on account B, where the SQS is located

Currently within the module we only have the possibility to make the subscription stay within account A (first scenario).
Using a subscription submodule, we can extend it to create, for example, the SNS (account A), then the SQS (account B), to later create your subscriptions separately within account B, which facilitates integration between accounts.

## Breaking Changes

Subscriptions that were already created using the old version will be recreated when using this new version. One possibility would be to use the terraform [moved](https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config) prevent this from happening, but it would be necessary to increase the terraform required_version to at least 1.1.
Reference:  [move-config](https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config)

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by matheusmazzoni** [comment]
@antonbabenko, could give your review? :D

**Comment by bryantbiggs** [comment]
I don't see the value in this change - why does creating a single resource sub-module solve the situation you described?

**Comment by matheusmazzoni** [comment]
@bryantbiggs, I will better express my idea and create a practical example in the code. The idea would be to separate the creation of the subscription from the SNS resource. Currently, if we want to create a subscription using a module, we are forced to pass the variable within the module to create the subscriptions together with the creation of the SNS topic. However, when we put it in a submodule, we can decentralize the responsibility of creating subscriptions from the creation of the SNS, although we still leave the possibility with the variable 'subscriptions.' To illustrate, imagine the following scenario:

I am using Terragrunt for creating an SNS and SQS cross-account integration. To achieve this, it creates the following folder structure:
```
├── account_x
    └── sns
        └── terragrunt.hcl
└── account_y
    └── sqs
        └── terragrunt.hcl
```
Inside the "sqs" folder, we will have the following "terragrunt.hcl" file:
```
include {
  path = find_in_parent_folders()
}
terraform {
  source = "tfr:///terraform-aws-modules/sqs/aws//?version=4.0.2"
}
dependency "sns" {
  config_path = "${get_terragrunt_dir()}/account_x/sns"
}

inputs = {
  create_queue_policy = true
  queue_policy_statements = {
    sns = {
      sid     = "SNSPublish"
      actions = ["sqs:SendMessage"]

      principals = [
        {
          type        = "Service"
          identifiers = ["sns.amazonaws.com"]
        }
      ]

      conditions = [{
        test     = "ArnEquals"
        variable = "aws:SourceArn"
        values = [dependency.sns.outputs.topic_arn]
      }]
    }
  }
}
```

We have a dependency on the SNS, as we need to grant access for sending messages from SNS to SQS. According to the documentation, when we create this dependency, both in Terragrunt and Terraform, we need to create the dependent resource first. Thus, we must create the SNS topic before applying the Terragrunt for the SQS. This is where the problem lies.

We have this Terragrunt file representing the current module for the SNS with the subscription created for the SQS
```
include {
  path = find_in_parent_folders()
}

terraform {
  source = "tfr:///terraform-aws-modules/sns/aws//?version=5.3.0"
}

dependency "sqs" {
  config_path = "${get_terragrunt_dir()}/account_y/sns"
}

inputs = {
  subscriptions = {
    catalog_deletion_sync_on_revision = {
      protocol      = "sqs"
      endpoint      = dependency.sqs.outputs.queue_arn
      filter_policy = jsonencode({ "eventType" : ["DELETION"] })
    }
  }

  topic_policy_statements = {
    devportal_subscribe = {
      effect = "Allow"
      actions = [
        "sns:Subscribe",
        "sns:Receive",
      ],
      principals = [{
        type        = "AWS"
        identifiers = ["*"]
      }]
    }
  }
}
```

We can notice that this module, to create the subscription, requires the previously created SQS. We face a challenge of cyclic reference. To create the SQS with the correct policy, we need to create the SNS first. However, to create the SNS with the subscription to the SQS, we need to create the SQS first. As a result, Terragrunt gets lost in this situation.

The solution I proposed would be to create a third resource, that is, a subscription submodule. By externalizing the subscription, we can first create the SNS without a subscription (without depending on the creation of the SQS). Then, we can create the SQS and move to the externalized subscription creation process.

**Comment by bryantbiggs** [comment]
> The solution I proposed would be to create a third resource, that is, a subscription submodule. By externalizing the subscription, we can first create the SNS without a subscription (without depending on the creation of the SQS). Then, we can create the SQS and move to the externalized subscription creation process.

Or just use a standalone subscription resource. I still don't see the benefit of having a single resource sub-module

**Comment by matheusmazzoni** [comment]
> > The solution I proposed would be to create a third resource, that is, a subscription submodule. By externalizing the subscription, we can first create the SNS without a subscription (without depending on the creation of the SQS). Then, we can create the SQS and move to the externalized subscription creation process.
> 
> Or just use a standalone subscription resource. I still don't see the benefit of having a single resource sub-module

You are right! The idea would be to decouple the subscription from the creation of an SNS topic, thus generating a submodule of a single resource. It's more visible in the context of using a wrapper, like terragrunt, but when we talk about "pure" terraform it makes no sense, right?

Thanks for your time :D

**Pull request closed without merging**
